import 'recipe_model.dart';

final List<Recipe> recipes = [
  Recipe(
    title: "Weizenmischbrot",
    description: "Der perfekte Einstieg: Außen knusprig, innen fluffig.",
    imageEmoji: "🥖",
    difficulty: "Anfänger",
    hydration: 70,
    unitName: "Brote",
    ingredients: "400g Weizenmehl (Type 550)\n100g Roggenmehl (Type 1150)\n350g lauwarmes Wasser\n100g aktiver Sauerteig\n12g Salz",
    steps: [
      RecipeStep(
        title: "Sauerteig-Check",
        durationMinutes: 5,
        temperature: "24°C",
        detailedInstructions: "Prüfe, ob dein Sauerteig fit ist. Er sollte sein Volumen verdoppelt haben und viele kleine Luftblasen zeigen.",
        techniqueExplanation: "Nur ein aktiver Sauerteig hat genug Kraft, um das Brot ohne Hefe zu heben.",
      ),
      RecipeStep(
        title: "Autolyse",
        durationMinutes: 45,
        temperature: "Zimmertemperatur",
        detailedInstructions: "Vermische Mehl und Wasser grob, bis kein trockenes Mehl mehr zu sehen ist. 45 Min. abgedeckt ruhen lassen.",
        techniqueExplanation: "Das Mehl saugt sich voll. Das macht den Teig später elastisch und leichter zu bearbeiten.",
      ),
      RecipeStep(
        title: "Hauptteig mischen",
        durationMinutes: 10,
        temperature: "22°C",
        detailedInstructions: "Sauerteig und Salz dazugeben. Kneten, bis der Teig glatt ist und sich vom Schüsselrand löst.",
        techniqueExplanation: "Salz stabilisiert das Gerüst und sorgt für die kräftige Kruste.",
      ),
      RecipeStep(
        title: "Dehnen & Falten",
        durationMinutes: 30,
        temperature: "24°C",
        detailedInstructions: "Greife unter den Teig, ziehe ihn hoch und falte ihn über die Mitte. Das Ganze viermal rundherum.",
        techniqueExplanation: "Strukturaufbau! So hält das Brot später seine Form und fließt nicht auseinander.",
      ),
      RecipeStep(
        title: "Stockgare",
        durationMinutes: 180,
        temperature: "24°C",
        detailedInstructions: "Den Teig ruhen lassen, bis er um ca. die Hälfte gewachsen ist. Er sollte luftig aussehen.",
      ),
      RecipeStep(
        title: "Formen",
        durationMinutes: 15,
        detailedInstructions: "Vorsichtig zum Laib formen und ins bemehlte Körbchen legen.",
        techniqueExplanation: "Oberflächenspannung ist das Geheimnis für einen tollen Ofentrieb.",
      ),
      RecipeStep(
        title: "Backen",
        durationMinutes: 45,
        temperature: "250°C",
        detailedInstructions: "Im Topf backen: 20 Min. mit Deckel, dann 25 Min. ohne Deckel für die Kruste.",
      ),
    ],
  ),
  Recipe(
    title: "Sauerteig Zimtschnecken",
    description: "Himmlisch fluffig und ohne Industriehefe. Ein Geduldsspiel, das sich lohnt.",
    imageEmoji: "🌀",
    difficulty: "Fortgeschritten",
    hydration: 60,
    unitName: "Bleche",
    ingredients: "500g Weizenmehl (Type 405)\n200g warme Milch\n100g weiche Butter\n80g Zucker\n150g aktiver Sauerteig\n5g Salz",
    steps: [
      RecipeStep(
        title: "Süßer Starter",
        durationMinutes: 15,
        temperature: "26°C",
        detailedInstructions: "Sauerteig mit warmer Milch, Zucker und etwas Mehl mischen. 2 Std. anspringen lassen.",
      ),
      RecipeStep(
        title: "Hauptteig kneten",
        durationMinutes: 20,
        detailedInstructions: "Restliche Zutaten und Butter schrittweise einkneten, bis der Teig glänzt.",
        techniqueExplanation: "Butter erst zum Schluss zugeben, damit das Mehl vorher gut binden kann.",
      ),
      RecipeStep(
        title: "Lange Stockgare",
        durationMinutes: 360,
        temperature: "Warm",
        detailedInstructions: "Der Teig muss sein Volumen fast verdoppeln. Das kann bei süßem Teig 6-8 Std. dauern.",
      ),
      RecipeStep(
        title: "Rollen & Schneiden",
        durationMinutes: 30,
        detailedInstructions: "Ausrollen, mit Zimtbutter bestreichen, einrollen und in dicke Scheiben schneiden.",
      ),
      RecipeStep(
        title: "Backen",
        durationMinutes: 25,
        temperature: "180°C O/U",
        detailedInstructions: "Goldbraun backen und noch warm glasieren.",
      ),
    ],
  ),
  Recipe(
    title: "Oliven-Ciabatta",
    description: "Großporig, rustikal und vollgepackt mit mediterranen Aromen.",
    imageEmoji: "🫒",
    difficulty: "Medium",
    hydration: 75,
    unitName: "Brote",
    ingredients: "500g Weizenmehl (Type 00)\n375g Wasser\n100g Sauerteig\n12g Salz\n80g Oliven\n1 Zweig Rosmarin",
    steps: [
      RecipeStep(
        title: "Mischen",
        durationMinutes: 10,
        detailedInstructions: "Mehl, Wasser und Sauerteig mischen. Der Teig ist sehr klebrig, das ist gewollt!",
      ),
      RecipeStep(
        title: "Laminieren",
        durationMinutes: 20,
        detailedInstructions: "Teig auf nasser Fläche ausziehen, Oliven und Rosmarin darauf verteilen und zusammenfalten.",
        techniqueExplanation: "So verteilen sich die Zutaten gleichmäßig, ohne die Luftblasen zu zerstören.",
      ),
      RecipeStep(
        title: "Stockgare",
        durationMinutes: 240,
        temperature: "Warm",
        detailedInstructions: "Lass den Teig ruhen, bis er vor Luftblasen fast platzt.",
      ),
      RecipeStep(
        title: "Backen",
        durationMinutes: 25,
        temperature: "240°C",
        detailedInstructions: "Mit viel Dampf backen, bis die Kruste goldgelb und krachig ist.",
      ),
    ],
  ),
  Recipe(
    title: "Mildes Landbrot",
    description: "Der Allrounder für jeden Tag mit 12 Std. Kühlschrank-Gare.",
    imageEmoji: "🍞",
    difficulty: "Anfänger",
    hydration: 68,
    unitName: "Brote",
    ingredients: "500g Weizenmehl (Type 1050)\n340g Wasser\n100g Sauerteig\n10g Salz",
    steps: [
      RecipeStep(
        title: "Mischen",
        durationMinutes: 15,
        detailedInstructions: "Alle Zutaten vermengen, bis ein homogener Teig entsteht.",
      ),
      RecipeStep(
        title: "Dehnen & Falten",
        durationMinutes: 120,
        detailedInstructions: "Während der ersten 2 Std. alle 30 Min. dehnen und falten.",
      ),
      RecipeStep(
        title: "Kalte Gare",
        durationMinutes: 720,
        temperature: "5°C",
        detailedInstructions: "Geformtes Brot über Nacht im Kühlschrank reifen lassen.",
        techniqueExplanation: "Baut Säure ab und macht das Brot extrem bekömmlich.",
      ),
      RecipeStep(
        title: "Backen",
        durationMinutes: 50,
        temperature: "230°C",
        detailedInstructions: "Direkt aus dem Kühlschrank in den heißen Ofen geben.",
      ),
    ],
  ),
];